from numpy import einsum
from numpy.typing import NDArray
from chem.hf.intermediates_builders import Intermediates
from chem.ccsd.uhf_ccsd import UHF_CCSD_Data


def get_lambda_singles_residual_aa(
    uhf_scf_data: Intermediates,
    uhf_ccsd_data: UHF_CCSD_Data,
) -> NDArray:
    f_aa = uhf_scf_data.f_aa
    f_bb = uhf_scf_data.f_bb
    g_aaaa = uhf_scf_data.g_aaaa
    g_abab = uhf_scf_data.g_abab
    g_bbbb = uhf_scf_data.g_bbbb
    va = uhf_scf_data.va
    vb = uhf_scf_data.vb
    oa = uhf_scf_data.oa
    ob = uhf_scf_data.ob
    t1_aa = uhf_ccsd_data.t1_aa
    t1_bb = uhf_ccsd_data.t1_bb
    t2_aaaa = uhf_ccsd_data.t2_aaaa
    t2_abab = uhf_ccsd_data.t2_abab
    t2_bbbb = uhf_ccsd_data.t2_bbbb
    if uhf_ccsd_data.lmbda is None:
        raise RuntimeError("Lambda amplitues missing in UHF_CCSD_Data")
    l1_aa = uhf_ccsd_data.lmbda.l1_aa
    l1_bb = uhf_ccsd_data.lmbda.l1_bb
    l2_aaaa = uhf_ccsd_data.lmbda.l2_aaaa
    l2_abab = uhf_ccsd_data.lmbda.l2_abab
    l2_bbbb = uhf_ccsd_data.lmbda.l2_bbbb
    
    lambda_singles_res_aa =  1.00 * einsum('ia->ai', f_aa[oa, va])
    lambda_singles_res_aa +=  1.00 * einsum('jj,ia->ai', f_aa[oa, oa], l1_aa)
    lambda_singles_res_aa +=  1.00 * einsum('jj,ia->ai', f_bb[ob, ob], l1_aa)
    lambda_singles_res_aa += -1.00 * einsum('ij,ja->ai', f_aa[oa, oa], l1_aa)
    lambda_singles_res_aa +=  1.00 * einsum('ba,ib->ai', f_aa[va, va], l1_aa)
    lambda_singles_res_aa += -1.00 * einsum('bj,ijba->ai', f_aa[va, oa], l2_aaaa)
    lambda_singles_res_aa +=  1.00 * einsum('bj,ijab->ai', f_bb[vb, ob], l2_abab)
    lambda_singles_res_aa +=  1.00 * einsum('jb,bj,ia->ai', f_aa[oa, va], t1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('jb,bj,ia->ai', f_bb[ob, vb], t1_bb, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ib,bj,ja->ai', f_aa[oa, va], t1_aa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ja,bj,ib->ai', f_aa[oa, va], t1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('kj,bk,ijba->ai', f_aa[oa, oa], t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('kj,bk,ijab->ai', f_bb[ob, ob], t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('bc,cj,ijba->ai', f_aa[va, va], t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('bc,cj,ijab->ai', f_bb[vb, vb], t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('kc,cbjk,ijba->ai', f_aa[oa, va], t2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('kc,cbkj,ijab->ai', f_aa[oa, va], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('kc,bcjk,ijba->ai', f_bb[ob, vb], t2_abab, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('kc,cbjk,ijab->ai', f_bb[ob, vb], t2_bbbb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ic,cbjk,jkba->ai', f_aa[oa, va], t2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ic,cbjk,jkab->ai', f_aa[oa, va], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ic,cbkj,kjab->ai', f_aa[oa, va], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ka,cbjk,ijcb->ai', f_aa[oa, va], t2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ka,cbkj,ijcb->ai', f_aa[oa, va], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ka,bckj,ijbc->ai', f_aa[oa, va], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('kc,bk,cj,ijba->ai', f_aa[oa, va], t1_aa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('kc,bk,cj,ijab->ai', f_bb[ob, vb], t1_bb, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('kjkj,ia->ai', g_aaaa[oa, oa, oa, oa], l1_aa)
    lambda_singles_res_aa += -0.50 * einsum('kjkj,ia->ai', g_abab[oa, ob, oa, ob], l1_aa)
    lambda_singles_res_aa += -0.50 * einsum('jkjk,ia->ai', g_abab[oa, ob, oa, ob], l1_aa)
    lambda_singles_res_aa += -0.50 * einsum('kjkj,ia->ai', g_bbbb[ob, ob, ob, ob], l1_aa)
    lambda_singles_res_aa +=  1.00 * einsum('ibaj,jb->ai', g_aaaa[oa, va, va, oa], l1_aa)
    lambda_singles_res_aa +=  1.00 * einsum('ibaj,jb->ai', g_abab[oa, vb, va, ob], l1_bb)
    lambda_singles_res_aa +=  0.50 * einsum('ibjk,jkba->ai', g_aaaa[oa, va, oa, oa], l2_aaaa)
    lambda_singles_res_aa += -0.50 * einsum('ibjk,jkab->ai', g_abab[oa, vb, oa, ob], l2_abab)
    lambda_singles_res_aa += -0.50 * einsum('ibkj,kjab->ai', g_abab[oa, vb, oa, ob], l2_abab)
    lambda_singles_res_aa +=  0.50 * einsum('cbaj,ijcb->ai', g_aaaa[va, va, va, oa], l2_aaaa)
    lambda_singles_res_aa +=  0.50 * einsum('cbaj,ijcb->ai', g_abab[va, vb, va, ob], l2_abab)
    lambda_singles_res_aa +=  0.50 * einsum('bcaj,ijbc->ai', g_abab[va, vb, va, ob], l2_abab)
    lambda_singles_res_aa += -1.00 * einsum('ijba,bj->ai', g_aaaa[oa, oa, va, va], t1_aa)
    lambda_singles_res_aa +=  1.00 * einsum('ijab,bj->ai', g_abab[oa, ob, va, vb], t1_bb)
    lambda_singles_res_aa +=  1.00 * einsum('ikbj,bk,ja->ai', g_aaaa[oa, oa, va, oa], t1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ikjb,bk,ja->ai', g_abab[oa, ob, oa, vb], t1_bb, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ikaj,bk,jb->ai', g_aaaa[oa, oa, va, oa], t1_aa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ikaj,bk,jb->ai', g_abab[oa, ob, va, ob], t1_bb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('jbca,cj,ib->ai', g_aaaa[oa, va, va, va], t1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('bjac,cj,ib->ai', g_abab[va, ob, va, vb], t1_bb, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ibca,cj,jb->ai', g_aaaa[oa, va, va, va], t1_aa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ibac,cj,jb->ai', g_abab[oa, vb, va, vb], t1_bb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('iljk,bl,jkba->ai', g_aaaa[oa, oa, oa, oa], t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('iljk,bl,jkab->ai', g_abab[oa, ob, oa, ob], t1_bb, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ilkj,bl,kjab->ai', g_abab[oa, ob, oa, ob], t1_bb, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('kbcj,ck,ijba->ai', g_aaaa[oa, va, va, oa], t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('kbcj,ck,ijab->ai', g_abab[oa, vb, va, ob], t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('bkjc,ck,ijba->ai', g_abab[va, ob, oa, vb], t1_bb, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('kbcj,ck,ijab->ai', g_bbbb[ob, vb, vb, ob], t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ibck,cj,jkba->ai', g_aaaa[oa, va, va, oa], t1_aa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ibck,cj,jkab->ai', g_abab[oa, vb, va, ob], t1_aa, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ibkc,cj,kjab->ai', g_abab[oa, vb, oa, vb], t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('kcaj,bk,ijcb->ai', g_aaaa[oa, va, va, oa], t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('kcaj,bk,ijbc->ai', g_abab[oa, vb, va, ob], t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ckaj,bk,ijcb->ai', g_abab[va, ob, va, ob], t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('cbda,dj,ijcb->ai', g_aaaa[va, va, va, va], t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('cbad,dj,ijcb->ai', g_abab[va, vb, va, vb], t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('bcad,dj,ijbc->ai', g_abab[va, vb, va, vb], t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('kjbc,bckj,ia->ai', g_aaaa[oa, oa, va, va], t2_aaaa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('kjbc,bckj,ia->ai', g_abab[oa, ob, va, vb], t2_abab, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('jkbc,bcjk,ia->ai', g_abab[oa, ob, va, vb], t2_abab, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('kjcb,cbkj,ia->ai', g_abab[oa, ob, va, vb], t2_abab, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('jkcb,cbjk,ia->ai', g_abab[oa, ob, va, vb], t2_abab, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('kjbc,bckj,ia->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ikbc,bcjk,ja->ai', g_aaaa[oa, oa, va, va], t2_aaaa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ikbc,bcjk,ja->ai', g_abab[oa, ob, va, vb], t2_abab, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ikcb,cbjk,ja->ai', g_abab[oa, ob, va, vb], t2_abab, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('kjca,cbkj,ib->ai', g_aaaa[oa, oa, va, va], t2_aaaa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('kjac,bckj,ib->ai', g_abab[oa, ob, va, vb], t2_abab, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('jkac,bcjk,ib->ai', g_abab[oa, ob, va, vb], t2_abab, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ikca,cbjk,jb->ai', g_aaaa[oa, oa, va, va], t2_aaaa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ikca,cbkj,jb->ai', g_aaaa[oa, oa, va, va], t2_abab, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ikac,bcjk,jb->ai', g_abab[oa, ob, va, vb], t2_abab, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ikac,cbjk,jb->ai', g_abab[oa, ob, va, vb], t2_bbbb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('lkcj,cblk,ijba->ai', g_aaaa[oa, oa, va, oa], t2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('lkcj,cblk,ijab->ai', g_abab[oa, ob, va, ob], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('klcj,cbkl,ijab->ai', g_abab[oa, ob, va, ob], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('lkjc,bclk,ijba->ai', g_abab[oa, ob, oa, vb], t2_abab, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('kljc,bckl,ijba->ai', g_abab[oa, ob, oa, vb], t2_abab, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('lkcj,cblk,ijab->ai', g_bbbb[ob, ob, vb, ob], t2_bbbb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ilck,cbjl,jkba->ai', g_aaaa[oa, oa, va, oa], t2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ilck,cbjl,jkab->ai', g_abab[oa, ob, va, ob], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ilck,cblj,kjab->ai', g_aaaa[oa, oa, va, oa], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ilkc,bcjl,jkba->ai', g_abab[oa, ob, oa, vb], t2_abab, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ilkc,cbjl,kjab->ai', g_abab[oa, ob, oa, vb], t2_bbbb, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('lkaj,cblk,ijcb->ai', g_aaaa[oa, oa, va, oa], t2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('lkaj,cblk,ijcb->ai', g_abab[oa, ob, va, ob], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('klaj,cbkl,ijcb->ai', g_abab[oa, ob, va, ob], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('lkaj,bclk,ijbc->ai', g_abab[oa, ob, va, ob], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('klaj,bckl,ijbc->ai', g_abab[oa, ob, va, ob], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilak,cbjl,jkcb->ai', g_aaaa[oa, oa, va, oa], t2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilak,cbjl,jkcb->ai', g_abab[oa, ob, va, ob], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilak,cblj,kjcb->ai', g_aaaa[oa, oa, va, oa], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilak,bcjl,jkbc->ai', g_abab[oa, ob, va, ob], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilak,bclj,kjbc->ai', g_aaaa[oa, oa, va, oa], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilak,cbjl,jkcb->ai', g_abab[oa, ob, va, ob], t2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('kbcd,cdjk,ijba->ai', g_aaaa[oa, va, va, va], t2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('bkcd,cdjk,ijba->ai', g_abab[va, ob, va, vb], t2_abab, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('kbcd,cdkj,ijab->ai', g_abab[oa, vb, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('bkdc,dcjk,ijba->ai', g_abab[va, ob, va, vb], t2_abab, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('kbdc,dckj,ijab->ai', g_abab[oa, vb, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('kbcd,cdjk,ijab->ai', g_bbbb[ob, vb, vb, vb], t2_bbbb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('ibcd,cdjk,jkba->ai', g_aaaa[oa, va, va, va], t2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.250 * einsum('ibcd,cdjk,jkab->ai', g_abab[oa, vb, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.250 * einsum('ibcd,cdkj,kjab->ai', g_abab[oa, vb, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.250 * einsum('ibdc,dcjk,jkab->ai', g_abab[oa, vb, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.250 * einsum('ibdc,dckj,kjab->ai', g_abab[oa, vb, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('kcda,dbjk,ijcb->ai', g_aaaa[oa, va, va, va], t2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('kcda,dbkj,ijcb->ai', g_aaaa[oa, va, va, va], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ckad,bdjk,ijcb->ai', g_abab[va, ob, va, vb], t2_abab, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('kcad,bdkj,ijbc->ai', g_abab[oa, vb, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ckad,dbjk,ijcb->ai', g_abab[va, ob, va, vb], t2_bbbb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('icda,dbjk,jkcb->ai', g_aaaa[oa, va, va, va], t2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('icda,dbjk,jkcb->ai', g_aaaa[oa, va, va, va], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('icda,dbkj,kjcb->ai', g_aaaa[oa, va, va, va], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('icad,bdjk,jkbc->ai', g_abab[oa, vb, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('icad,bdkj,kjbc->ai', g_abab[oa, vb, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('icad,dbjk,jkcb->ai', g_abab[oa, vb, va, vb], t2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('lkcd,dbjl,ck,ijba->ai', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('lkdc,dbjl,ck,ijba->ai', g_abab[oa, ob, va, vb], t2_aaaa, t1_bb, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('lkcd,dblj,ck,ijab->ai', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('lkdc,dblj,ck,ijab->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('klcd,bdjl,ck,ijba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('lkcd,bdjl,ck,ijba->ai', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('klcd,dbjl,ck,ijab->ai', g_abab[oa, ob, va, vb], t2_bbbb, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('lkcd,dbjl,ck,ijab->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilcd,dbjk,cl,jkba->ai', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ildc,dbjk,cl,jkba->ai', g_abab[oa, ob, va, vb], t2_aaaa, t1_bb, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ilcd,dbjk,cl,jkab->ai', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ildc,dbjk,cl,jkab->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ilcd,dbkj,cl,kjab->ai', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ildc,dbkj,cl,kjab->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('lkda,cbjl,dk,ijcb->ai', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('lkad,cbjl,dk,ijcb->ai', g_abab[oa, ob, va, vb], t2_aaaa, t1_bb, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('lkda,cblj,dk,ijcb->ai', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('lkad,cblj,dk,ijcb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('lkda,bclj,dk,ijbc->ai', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('lkad,bclj,dk,ijbc->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('lkcd,dblk,cj,ijba->ai', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('lkdc,dblk,cj,ijab->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('kldc,dbkl,cj,ijab->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('lkcd,bdlk,cj,ijba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('klcd,bdkl,cj,ijba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('lkcd,dblk,cj,ijab->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ilcd,dbjl,ck,jkba->ai', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, l2_aaaa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ildc,dbjl,ck,jkab->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ilcd,dblj,ck,kjab->ai', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ilcd,bdjl,ck,jkba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_aaaa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ilcd,dbjl,ck,kjab->ai', g_abab[oa, ob, va, vb], t2_bbbb, t1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.250 * einsum('lkda,cblk,dj,ijcb->ai', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('lkad,cblk,dj,ijcb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('klad,cbkl,dj,ijcb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('lkad,bclk,dj,ijbc->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('klad,bckl,dj,ijbc->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ilda,cbjl,dk,jkcb->ai', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, l2_aaaa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilad,cbjl,dk,jkcb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ilda,cblj,dk,kjcb->ai', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilad,bcjl,dk,jkbc->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ilda,bclj,dk,kjbc->ai', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilad,cbjl,dk,jkcb->ai', g_abab[oa, ob, va, vb], t2_bbbb, t1_bb, l2_bbbb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('lkcd,bk,cdjl,ijba->ai', g_aaaa[oa, oa, va, va], t1_aa, t2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('klcd,bk,cdjl,ijba->ai', g_abab[oa, ob, va, vb], t1_aa, t2_abab, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('kldc,bk,dcjl,ijba->ai', g_abab[oa, ob, va, vb], t1_aa, t2_abab, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('lkcd,bk,cdlj,ijab->ai', g_abab[oa, ob, va, vb], t1_bb, t2_abab, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('lkdc,bk,dclj,ijab->ai', g_abab[oa, ob, va, vb], t1_bb, t2_abab, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('lkcd,bk,cdjl,ijab->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t2_bbbb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -0.250 * einsum('ilcd,bl,cdjk,jkba->ai', g_aaaa[oa, oa, va, va], t1_aa, t2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('ilcd,bl,cdjk,jkab->ai', g_abab[oa, ob, va, vb], t1_bb, t2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('ilcd,bl,cdkj,kjab->ai', g_abab[oa, ob, va, vb], t1_bb, t2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('ildc,bl,dcjk,jkab->ai', g_abab[oa, ob, va, vb], t1_bb, t2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.250 * einsum('ildc,bl,dckj,kjab->ai', g_abab[oa, ob, va, vb], t1_bb, t2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('lkda,dbjl,ck,ijcb->ai', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('lkda,dblj,ck,ijcb->ai', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('klad,bdjl,ck,ijcb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('lkad,bdlj,ck,ijbc->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('klad,dbjl,ck,ijcb->ai', g_abab[oa, ob, va, vb], t2_bbbb, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ilda,dbjk,cl,jkcb->ai', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, l2_aaaa, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ilda,dbjk,cl,jkcb->ai', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ilda,dbkj,cl,kjcb->ai', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilad,bdjk,cl,jkbc->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilad,bdkj,cl,kjbc->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ilad,dbjk,cl,jkcb->ai', g_abab[oa, ob, va, vb], t2_bbbb, t1_bb, l2_bbbb, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('kjbc,bj,ck,ia->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('jkbc,bj,ck,ia->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, l1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('kjcb,bj,ck,ia->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('kjbc,bj,ck,ia->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, l1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ikbc,bk,cj,ja->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ikcb,bk,cj,ja->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('kjca,bk,cj,ib->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, l1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('kjac,bk,cj,ib->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, l1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ikca,bk,cj,jb->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, l1_aa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ikac,bk,cj,jb->ai', g_abab[oa, ob, va, vb], t1_bb, t1_bb, l1_bb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('lkcj,bl,ck,ijba->ai', g_aaaa[oa, oa, va, oa], t1_aa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('lkjc,bl,ck,ijba->ai', g_abab[oa, ob, oa, vb], t1_aa, t1_bb, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('klcj,bl,ck,ijab->ai', g_abab[oa, ob, va, ob], t1_bb, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('lkcj,bl,ck,ijab->ai', g_bbbb[ob, ob, vb, ob], t1_bb, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ilck,bl,cj,jkba->ai', g_aaaa[oa, oa, va, oa], t1_aa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ilck,bl,cj,jkab->ai', g_abab[oa, ob, va, ob], t1_bb, t1_aa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('ilkc,bl,cj,kjab->ai', g_abab[oa, ob, oa, vb], t1_bb, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('lkaj,bl,ck,ijcb->ai', g_aaaa[oa, oa, va, oa], t1_aa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('lkaj,bl,ck,ijbc->ai', g_abab[oa, ob, va, ob], t1_aa, t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('klaj,bl,ck,ijcb->ai', g_abab[oa, ob, va, ob], t1_bb, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('kbcd,ck,dj,ijba->ai', g_aaaa[oa, va, va, va], t1_aa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('kbcd,ck,dj,ijab->ai', g_abab[oa, vb, va, vb], t1_aa, t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('bkdc,ck,dj,ijba->ai', g_abab[va, ob, va, vb], t1_bb, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('kbcd,ck,dj,ijab->ai', g_bbbb[ob, vb, vb, vb], t1_bb, t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ibcd,ck,dj,jkba->ai', g_aaaa[oa, va, va, va], t1_aa, t1_aa, l2_aaaa, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ibcd,ck,dj,kjab->ai', g_abab[oa, vb, va, vb], t1_aa, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_aa += -0.50 * einsum('ibdc,ck,dj,jkab->ai', g_abab[oa, vb, va, vb], t1_bb, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('kcda,bk,dj,ijcb->ai', g_aaaa[oa, va, va, va], t1_aa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('kcad,bk,dj,ijbc->ai', g_abab[oa, vb, va, vb], t1_aa, t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('ckad,bk,dj,ijcb->ai', g_abab[va, ob, va, vb], t1_bb, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('lkcd,bl,ck,dj,ijba->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 3), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('lkdc,bl,ck,dj,ijba->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 3), (0, 2), (0, 1)])
    lambda_singles_res_aa += -1.00 * einsum('klcd,bl,ck,dj,ijab->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (1, 3), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  1.00 * einsum('lkcd,bl,ck,dj,ijab->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (1, 3), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ilcd,bl,ck,dj,jkba->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ilcd,bl,ck,dj,kjab->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, t1_bb, l2_abab, optimize=['einsum_path', (0, 3), (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('ildc,bl,ck,dj,jkab->ai', g_abab[oa, ob, va, vb], t1_bb, t1_bb, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('lkda,bl,ck,dj,ijcb->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, t1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 3), (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('lkad,bl,ck,dj,ijbc->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_aa +=  0.50 * einsum('klad,bl,ck,dj,ijcb->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1), (0, 1)])
    return lambda_singles_res_aa


def get_lambda_singles_residual_bb(
    uhf_scf_data: Intermediates,
    uhf_ccsd_data: UHF_CCSD_Data,
) -> NDArray:
    f_aa = uhf_scf_data.f_aa
    f_bb = uhf_scf_data.f_bb
    g_aaaa = uhf_scf_data.g_aaaa
    g_abab = uhf_scf_data.g_abab
    g_bbbb = uhf_scf_data.g_bbbb
    va = uhf_scf_data.va
    vb = uhf_scf_data.vb
    oa = uhf_scf_data.oa
    ob = uhf_scf_data.ob
    t1_aa = uhf_ccsd_data.t1_aa
    t1_bb = uhf_ccsd_data.t1_bb
    t2_aaaa = uhf_ccsd_data.t2_aaaa
    t2_abab = uhf_ccsd_data.t2_abab
    t2_bbbb = uhf_ccsd_data.t2_bbbb
    if uhf_ccsd_data.lmbda is None:
        raise RuntimeError("Lambda amplitues missing in UHF_CCSD_Data")
    l1_aa = uhf_ccsd_data.lmbda.l1_aa
    l1_bb = uhf_ccsd_data.lmbda.l1_bb
    l2_aaaa = uhf_ccsd_data.lmbda.l2_aaaa
    l2_abab = uhf_ccsd_data.lmbda.l2_abab
    l2_bbbb = uhf_ccsd_data.lmbda.l2_bbbb
    
    lambda_singles_res_bb =  1.00 * einsum('ia->ai', f_bb[ob, vb])
    lambda_singles_res_bb +=  1.00 * einsum('jj,ia->ai', f_aa[oa, oa], l1_bb)
    lambda_singles_res_bb +=  1.00 * einsum('jj,ia->ai', f_bb[ob, ob], l1_bb)
    lambda_singles_res_bb += -1.00 * einsum('ij,ja->ai', f_bb[ob, ob], l1_bb)
    lambda_singles_res_bb +=  1.00 * einsum('ba,ib->ai', f_bb[vb, vb], l1_bb)
    lambda_singles_res_bb +=  1.00 * einsum('bj,jiba->ai', f_aa[va, oa], l2_abab)
    lambda_singles_res_bb += -1.00 * einsum('bj,ijba->ai', f_bb[vb, ob], l2_bbbb)
    lambda_singles_res_bb +=  1.00 * einsum('jb,bj,ia->ai', f_aa[oa, va], t1_aa, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('jb,bj,ia->ai', f_bb[ob, vb], t1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('ib,bj,ja->ai', f_bb[ob, vb], t1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('ja,bj,ib->ai', f_bb[ob, vb], t1_bb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kj,bk,jiba->ai', f_aa[oa, oa], t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('kj,bk,ijba->ai', f_bb[ob, ob], t1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('bc,cj,jiba->ai', f_aa[va, va], t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('bc,cj,ijba->ai', f_bb[vb, vb], t1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kc,cbjk,jiba->ai', f_aa[oa, va], t2_aaaa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kc,cbkj,ijba->ai', f_aa[oa, va], t2_abab, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('kc,bcjk,jiba->ai', f_bb[ob, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('kc,cbjk,ijba->ai', f_bb[ob, vb], t2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('ic,bcjk,jkba->ai', f_bb[ob, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('ic,bckj,kjba->ai', f_bb[ob, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('ic,cbjk,jkba->ai', f_bb[ob, vb], t2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('ka,cbjk,jicb->ai', f_bb[ob, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('ka,bcjk,jibc->ai', f_bb[ob, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('ka,cbjk,ijcb->ai', f_bb[ob, vb], t2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kc,bk,cj,jiba->ai', f_aa[oa, va], t1_aa, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('kc,bk,cj,ijba->ai', f_bb[ob, vb], t1_bb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('kjkj,ia->ai', g_aaaa[oa, oa, oa, oa], l1_bb)
    lambda_singles_res_bb += -0.50 * einsum('kjkj,ia->ai', g_abab[oa, ob, oa, ob], l1_bb)
    lambda_singles_res_bb += -0.50 * einsum('jkjk,ia->ai', g_abab[oa, ob, oa, ob], l1_bb)
    lambda_singles_res_bb += -0.50 * einsum('kjkj,ia->ai', g_bbbb[ob, ob, ob, ob], l1_bb)
    lambda_singles_res_bb +=  1.00 * einsum('bija,jb->ai', g_abab[va, ob, oa, vb], l1_aa)
    lambda_singles_res_bb +=  1.00 * einsum('ibaj,jb->ai', g_bbbb[ob, vb, vb, ob], l1_bb)
    lambda_singles_res_bb += -0.50 * einsum('bijk,jkba->ai', g_abab[va, ob, oa, ob], l2_abab)
    lambda_singles_res_bb += -0.50 * einsum('bikj,kjba->ai', g_abab[va, ob, oa, ob], l2_abab)
    lambda_singles_res_bb +=  0.50 * einsum('ibjk,jkba->ai', g_bbbb[ob, vb, ob, ob], l2_bbbb)
    lambda_singles_res_bb +=  0.50 * einsum('cbja,jicb->ai', g_abab[va, vb, oa, vb], l2_abab)
    lambda_singles_res_bb +=  0.50 * einsum('bcja,jibc->ai', g_abab[va, vb, oa, vb], l2_abab)
    lambda_singles_res_bb +=  0.50 * einsum('cbaj,ijcb->ai', g_bbbb[vb, vb, vb, ob], l2_bbbb)
    lambda_singles_res_bb +=  1.00 * einsum('jiba,bj->ai', g_abab[oa, ob, va, vb], t1_aa)
    lambda_singles_res_bb += -1.00 * einsum('ijba,bj->ai', g_bbbb[ob, ob, vb, vb], t1_bb)
    lambda_singles_res_bb += -1.00 * einsum('kibj,bk,ja->ai', g_abab[oa, ob, va, ob], t1_aa, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('ikbj,bk,ja->ai', g_bbbb[ob, ob, vb, ob], t1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kija,bk,jb->ai', g_abab[oa, ob, oa, vb], t1_aa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('ikaj,bk,jb->ai', g_bbbb[ob, ob, vb, ob], t1_bb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('jbca,cj,ib->ai', g_abab[oa, vb, va, vb], t1_aa, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('jbca,cj,ib->ai', g_bbbb[ob, vb, vb, vb], t1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('bica,cj,jb->ai', g_abab[va, ob, va, vb], t1_aa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('ibca,cj,jb->ai', g_bbbb[ob, vb, vb, vb], t1_bb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lijk,bl,jkba->ai', g_abab[oa, ob, oa, ob], t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('likj,bl,kjba->ai', g_abab[oa, ob, oa, ob], t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('iljk,bl,jkba->ai', g_bbbb[ob, ob, ob, ob], t1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('kbcj,ck,jiba->ai', g_aaaa[oa, va, va, oa], t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kbcj,ck,ijba->ai', g_abab[oa, vb, va, ob], t1_aa, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('bkjc,ck,jiba->ai', g_abab[va, ob, oa, vb], t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kbcj,ck,ijba->ai', g_bbbb[ob, vb, vb, ob], t1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('bick,cj,jkba->ai', g_abab[va, ob, va, ob], t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('bikc,cj,kjba->ai', g_abab[va, ob, oa, vb], t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('ibck,cj,jkba->ai', g_bbbb[ob, vb, vb, ob], t1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kcja,bk,jibc->ai', g_abab[oa, vb, oa, vb], t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('ckja,bk,jicb->ai', g_abab[va, ob, oa, vb], t1_bb, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('kcaj,bk,ijcb->ai', g_bbbb[ob, vb, vb, ob], t1_bb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('cbda,dj,jicb->ai', g_abab[va, vb, va, vb], t1_aa, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('bcda,dj,jibc->ai', g_abab[va, vb, va, vb], t1_aa, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('cbda,dj,ijcb->ai', g_bbbb[vb, vb, vb, vb], t1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('kjbc,bckj,ia->ai', g_aaaa[oa, oa, va, va], t2_aaaa, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('kjbc,bckj,ia->ai', g_abab[oa, ob, va, vb], t2_abab, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('jkbc,bcjk,ia->ai', g_abab[oa, ob, va, vb], t2_abab, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('kjcb,cbkj,ia->ai', g_abab[oa, ob, va, vb], t2_abab, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('jkcb,cbjk,ia->ai', g_abab[oa, ob, va, vb], t2_abab, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('kjbc,bckj,ia->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('kibc,bckj,ja->ai', g_abab[oa, ob, va, vb], t2_abab, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('kicb,cbkj,ja->ai', g_abab[oa, ob, va, vb], t2_abab, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('ikbc,bcjk,ja->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('kjca,cbkj,ib->ai', g_abab[oa, ob, va, vb], t2_abab, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('jkca,cbjk,ib->ai', g_abab[oa, ob, va, vb], t2_abab, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('kjca,cbkj,ib->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kica,cbjk,jb->ai', g_abab[oa, ob, va, vb], t2_aaaa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('kica,cbkj,jb->ai', g_abab[oa, ob, va, vb], t2_abab, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('ikca,bcjk,jb->ai', g_bbbb[ob, ob, vb, vb], t2_abab, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('ikca,cbjk,jb->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lkcj,cblk,jiba->ai', g_aaaa[oa, oa, va, oa], t2_aaaa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lkcj,cblk,ijba->ai', g_abab[oa, ob, va, ob], t2_abab, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('klcj,cbkl,ijba->ai', g_abab[oa, ob, va, ob], t2_abab, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lkjc,bclk,jiba->ai', g_abab[oa, ob, oa, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('kljc,bckl,jiba->ai', g_abab[oa, ob, oa, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lkcj,cblk,ijba->ai', g_bbbb[ob, ob, vb, ob], t2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('lick,cbjl,jkba->ai', g_abab[oa, ob, va, ob], t2_aaaa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('lick,cblj,jkba->ai', g_abab[oa, ob, va, ob], t2_abab, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('ilck,bcjl,jkba->ai', g_bbbb[ob, ob, vb, ob], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('likc,bclj,kjba->ai', g_abab[oa, ob, oa, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('ilck,cbjl,jkba->ai', g_bbbb[ob, ob, vb, ob], t2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('lkja,cblk,jicb->ai', g_abab[oa, ob, oa, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('klja,cbkl,jicb->ai', g_abab[oa, ob, oa, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('lkja,bclk,jibc->ai', g_abab[oa, ob, oa, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('klja,bckl,jibc->ai', g_abab[oa, ob, oa, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('lkaj,cblk,ijcb->ai', g_bbbb[ob, ob, vb, ob], t2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lika,cbjl,jkcb->ai', g_abab[oa, ob, oa, vb], t2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('ilak,cbjl,jkcb->ai', g_bbbb[ob, ob, vb, ob], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lika,cblj,kjcb->ai', g_abab[oa, ob, oa, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('ilak,bcjl,jkbc->ai', g_bbbb[ob, ob, vb, ob], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lika,bclj,kjbc->ai', g_abab[oa, ob, oa, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('ilak,cbjl,jkcb->ai', g_bbbb[ob, ob, vb, ob], t2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('kbcd,cdjk,jiba->ai', g_aaaa[oa, va, va, va], t2_aaaa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('bkcd,cdjk,jiba->ai', g_abab[va, ob, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('kbcd,cdkj,ijba->ai', g_abab[oa, vb, va, vb], t2_abab, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('bkdc,dcjk,jiba->ai', g_abab[va, ob, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('kbdc,dckj,ijba->ai', g_abab[oa, vb, va, vb], t2_abab, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('kbcd,cdjk,ijba->ai', g_bbbb[ob, vb, vb, vb], t2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.250 * einsum('bicd,cdjk,jkba->ai', g_abab[va, ob, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.250 * einsum('bicd,cdkj,kjba->ai', g_abab[va, ob, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.250 * einsum('bidc,dcjk,jkba->ai', g_abab[va, ob, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.250 * einsum('bidc,dckj,kjba->ai', g_abab[va, ob, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('ibcd,cdjk,jkba->ai', g_bbbb[ob, vb, vb, vb], t2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kcda,dbjk,jibc->ai', g_abab[oa, vb, va, vb], t2_aaaa, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('ckda,dbjk,jicb->ai', g_abab[va, ob, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('kcda,dbkj,ijcb->ai', g_abab[oa, vb, va, vb], t2_abab, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('kcda,bdjk,jibc->ai', g_bbbb[ob, vb, vb, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kcda,dbjk,ijcb->ai', g_bbbb[ob, vb, vb, vb], t2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('cida,dbjk,jkcb->ai', g_abab[va, ob, va, vb], t2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('cida,dbjk,jkcb->ai', g_abab[va, ob, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('cida,dbkj,kjcb->ai', g_abab[va, ob, va, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('icda,bdjk,jkbc->ai', g_bbbb[ob, vb, vb, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('icda,bdkj,kjbc->ai', g_bbbb[ob, vb, vb, vb], t2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('icda,dbjk,jkcb->ai', g_bbbb[ob, vb, vb, vb], t2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('lkcd,dbjl,ck,jiba->ai', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('lkdc,dbjl,ck,jiba->ai', g_abab[oa, ob, va, vb], t2_aaaa, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('lkcd,dblj,ck,ijba->ai', g_aaaa[oa, oa, va, va], t2_abab, t1_aa, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('lkdc,dblj,ck,ijba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('klcd,bdjl,ck,jiba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('lkcd,bdjl,ck,jiba->ai', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('klcd,dbjl,ck,ijba->ai', g_abab[oa, ob, va, vb], t2_bbbb, t1_aa, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('lkcd,dbjl,ck,ijba->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('licd,bdjk,cl,jkba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('ilcd,bdjk,cl,jkba->ai', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('licd,bdkj,cl,kjba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('ilcd,bdkj,cl,kjba->ai', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('licd,dbjk,cl,jkba->ai', g_abab[oa, ob, va, vb], t2_bbbb, t1_aa, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('ilcd,dbjk,cl,jkba->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('klda,cbjl,dk,jicb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lkda,cbjl,dk,jicb->ai', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('klda,bcjl,dk,jibc->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lkda,bcjl,dk,jibc->ai', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('klda,cbjl,dk,ijcb->ai', g_abab[oa, ob, va, vb], t2_bbbb, t1_aa, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lkda,cbjl,dk,ijcb->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lkcd,dblk,cj,jiba->ai', g_aaaa[oa, oa, va, va], t2_aaaa, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lkdc,dblk,cj,ijba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('kldc,dbkl,cj,ijba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lkcd,bdlk,cj,jiba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('klcd,bdkl,cj,jiba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lkcd,dblk,cj,ijba->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('lidc,dbjl,ck,jkba->ai', g_abab[oa, ob, va, vb], t2_aaaa, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('lidc,dblj,ck,jkba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('ilcd,bdjl,ck,jkba->ai', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('licd,bdlj,ck,kjba->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('ilcd,dbjl,ck,jkba->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('lkda,cblk,dj,jicb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('klda,cbkl,dj,jicb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('lkda,bclk,dj,jibc->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('klda,bckl,dj,jibc->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.250 * einsum('lkda,cblk,dj,ijcb->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lida,cbjl,dk,jkcb->ai', g_abab[oa, ob, va, vb], t2_aaaa, t1_aa, l2_aaaa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('ilda,cbjl,dk,jkcb->ai', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lida,cblj,dk,kjcb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('ilda,bcjl,dk,jkbc->ai', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lida,bclj,dk,kjbc->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('ilda,cbjl,dk,jkcb->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, l2_bbbb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lkcd,bk,cdjl,jiba->ai', g_aaaa[oa, oa, va, va], t1_aa, t2_aaaa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('klcd,bk,cdjl,jiba->ai', g_abab[oa, ob, va, vb], t1_aa, t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('kldc,bk,dcjl,jiba->ai', g_abab[oa, ob, va, vb], t1_aa, t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lkcd,bk,cdlj,ijba->ai', g_abab[oa, ob, va, vb], t1_bb, t2_abab, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lkdc,bk,dclj,ijba->ai', g_abab[oa, ob, va, vb], t1_bb, t2_abab, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lkcd,bk,cdjl,ijba->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('licd,bl,cdjk,jkba->ai', g_abab[oa, ob, va, vb], t1_aa, t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('licd,bl,cdkj,kjba->ai', g_abab[oa, ob, va, vb], t1_aa, t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('lidc,bl,dcjk,jkba->ai', g_abab[oa, ob, va, vb], t1_aa, t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.250 * einsum('lidc,bl,dckj,kjba->ai', g_abab[oa, ob, va, vb], t1_aa, t2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.250 * einsum('ilcd,bl,cdjk,jkba->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('lkda,dbjl,ck,jibc->ai', g_abab[oa, ob, va, vb], t2_aaaa, t1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('klda,dbjl,ck,jicb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('lkda,dblj,ck,ijcb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_bb, l2_bbbb, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('lkda,bdjl,ck,jibc->ai', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('lkda,dbjl,ck,ijcb->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, l2_bbbb, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lida,dbjk,cl,jkcb->ai', g_abab[oa, ob, va, vb], t2_aaaa, t1_aa, l2_aaaa, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lida,dbjk,cl,jkcb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lida,dbkj,cl,kjcb->ai', g_abab[oa, ob, va, vb], t2_abab, t1_aa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('ilda,bdjk,cl,jkbc->ai', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('ilda,bdkj,cl,kjbc->ai', g_bbbb[ob, ob, vb, vb], t2_abab, t1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('ilda,dbjk,cl,jkcb->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, t1_bb, l2_bbbb, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('kjbc,bj,ck,ia->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, l1_bb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('jkbc,bj,ck,ia->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('kjcb,bj,ck,ia->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, l1_bb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('kjbc,bj,ck,ia->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kibc,bk,cj,ja->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('ikbc,bk,cj,ja->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('jkca,bk,cj,ib->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, l1_bb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('kjca,bk,cj,ib->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, l1_bb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kica,bk,cj,jb->ai', g_abab[oa, ob, va, vb], t1_aa, t1_aa, l1_aa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('ikca,bk,cj,jb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, l1_bb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('lkcj,bl,ck,jiba->ai', g_aaaa[oa, oa, va, oa], t1_aa, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('lkjc,bl,ck,jiba->ai', g_abab[oa, ob, oa, vb], t1_aa, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('klcj,bl,ck,ijba->ai', g_abab[oa, ob, va, ob], t1_bb, t1_aa, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('lkcj,bl,ck,ijba->ai', g_bbbb[ob, ob, vb, ob], t1_bb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('lick,bl,cj,jkba->ai', g_abab[oa, ob, va, ob], t1_aa, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('likc,bl,cj,kjba->ai', g_abab[oa, ob, oa, vb], t1_aa, t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('ilck,bl,cj,jkba->ai', g_bbbb[ob, ob, vb, ob], t1_bb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lkja,bl,ck,jibc->ai', g_abab[oa, ob, oa, vb], t1_aa, t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('klja,bl,ck,jicb->ai', g_abab[oa, ob, oa, vb], t1_bb, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('lkaj,bl,ck,ijcb->ai', g_bbbb[ob, ob, vb, ob], t1_bb, t1_bb, l2_bbbb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('kbcd,ck,dj,jiba->ai', g_aaaa[oa, va, va, va], t1_aa, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kbcd,ck,dj,ijba->ai', g_abab[oa, vb, va, vb], t1_aa, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('bkdc,ck,dj,jiba->ai', g_abab[va, ob, va, vb], t1_bb, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kbcd,ck,dj,ijba->ai', g_bbbb[ob, vb, vb, vb], t1_bb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('bicd,ck,dj,kjba->ai', g_abab[va, ob, va, vb], t1_aa, t1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('bidc,ck,dj,jkba->ai', g_abab[va, ob, va, vb], t1_bb, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_bb += -0.50 * einsum('ibcd,ck,dj,jkba->ai', g_bbbb[ob, vb, vb, vb], t1_bb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kcda,bk,dj,jibc->ai', g_abab[oa, vb, va, vb], t1_aa, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('ckda,bk,dj,jicb->ai', g_abab[va, ob, va, vb], t1_bb, t1_aa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('kcda,bk,dj,ijcb->ai', g_bbbb[ob, vb, vb, vb], t1_bb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('lkcd,bl,ck,dj,jiba->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 3), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('lkdc,bl,ck,dj,jiba->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 3), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  1.00 * einsum('klcd,bl,ck,dj,ijba->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (1, 3), (0, 2), (0, 1)])
    lambda_singles_res_bb += -1.00 * einsum('lkcd,bl,ck,dj,ijba->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (1, 3), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('licd,bl,ck,dj,kjba->ai', g_abab[oa, ob, va, vb], t1_aa, t1_aa, t1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lidc,bl,ck,dj,jkba->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 3), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('ilcd,bl,ck,dj,jkba->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lkda,bl,ck,dj,jibc->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, t1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('klda,bl,ck,dj,jicb->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, t1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 2), (0, 1)])
    lambda_singles_res_bb +=  0.50 * einsum('lkda,bl,ck,dj,ijcb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, t1_bb, l2_bbbb, optimize=['einsum_path', (0, 3), (0, 2), (0, 2), (0, 1)])
    return lambda_singles_res_bb
